apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcl-controller
  labels:
    control-plane: controller
spec:
  selector:
    matchLabels:
      app: kcl-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: kcl-controller
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8083"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: manager
          image: kcl-controller
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8083
              name: http-prom
          env:
            - name: RUNTIME_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - --log-level=info
            - --enable-leader-election
          livenessProbe:
            httpGet:
              port: http-prom
              path: /metrics
          readinessProbe:
            httpGet:
              port: http-prom
              path: /metrics
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}

