---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: source-reader
rules:
- apiGroups:
  - krm.kcl.dev.fluxcd
  resources:
  - kclruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - krm.kcl.dev.fluxcd
  resources:
  - kclruns/finalizers
  verbs:
  - update
- apiGroups:
  - krm.kcl.dev.fluxcd
  resources:
  - kclruns/status
  verbs:
  - get
  - patch
  - update
