name: test

on:
  pull_request:
  push:
    branches:
      - main
      - test*

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: 1.22
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      - name: Run tests
        run: make test
